import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { PageHeader, StatCard } from "@/components/shared";
import { KES, salesTrend, paymentSplit, topProducts, aiInsights, branches } from "@/lib/mock-data";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogTrigger } from "@/components/ui/dialog";
import {
  Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis,
  PieChart, Pie, Cell, BarChart, Bar, CartesianGrid,
} from "recharts";
import {
  TrendingUp, Wallet, ShoppingBag, Receipt, Sparkles, ArrowRight,
  FileText, MessageCircle, Download, Send, CheckCircle2, AlertTriangle, Copy, Bot
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/dashboard")({
  head: () => ({ meta: [{ title: "Dashboard — KaliPOS" }, { name: "description", content: "Live sales, profit, AI insights for your shop." }] }),
  component: Dashboard,
});

function Dashboard() {
  const navigate = useNavigate();
  const [reportOpen, setReportOpen] = useState(false);
  const [aiModalOpen, setAiModalOpen] = useState(false);
  const [aiQuestion, setAiQuestion] = useState("");
  const [aiAnswer, setAiAnswer] = useState<string | null>(null);
  const [isAiLoading, setIsAiLoading] = useState(false);

  // Send Report to WhatsApp Action
  const handleSendReportWhatsApp = () => {
    const dateStr = new Date().toLocaleDateString("en-KE", { weekday: "short", day: "numeric", month: "short", year: "numeric" });
    const text = `📊 *Kato's Kitchen Close-of-Business AI Summary (${dateStr})*%0A%0A` +
      `💰 *Total Sales:* ${KES(58420)}%0A` +
      `📈 *Net Profit:* ${KES(16780)} (28.7% margin)%0A` +
      `🧾 *Transactions:* 184 orders%0A` +
      `📱 *M-Pesa Reconciled:* ${KES(42062)} (100% matched)%0A%0A` +
      `🍛 *Top Dishes:*%0A` +
      `1. Nyama Choma (84 plates)%0A` +
      `2. Brown Ugali (132 plates)%0A` +
      `3. Pilau ya Kuku (76 plates)%0A%0A` +
      `🛒 *Market Restock Needed:* Fresh Tilapia, Tomatoes, Chicken%0A%0A` +
      `Generated by KaliPOS Smart Retail 🇰🇪`;

    window.open(`https://wa.me/?text=${text}`, "_blank");
    toast.success("Opening WhatsApp with Close-of-Business Report 💬");
  };

  // AI Prompt Helper
  const handleAskAi = (query: string) => {
    setAiQuestion(query);
    setIsAiLoading(true);
    setAiAnswer(null);

    setTimeout(() => {
      let response = "";
      if (query.toLowerCase().includes("least profit") || query.toLowerCase().includes("margin")) {
        response = "Cooking Fat and Sugar had the lowest margins this week (~12% drop due to wholesale costs). Suggestion: Increase sugar shelf price by KSh 15 or negotiate bulk rates with Bidco Africa.";
      } else if (query.toLowerCase().includes("reorder") || query.toLowerCase().includes("stock")) {
        response = "Restock within 24 hours: Fresh Tilapia (4 kg left), Tomatoes (3 kg left), and Brookside Milk (12 pkts left). Total estimated market cost: KSh 7,650.";
      } else if (query.toLowerCase().includes("busiest") || query.toLowerCase().includes("hours")) {
        response = "Peak sales hours are 12:00 PM – 2:00 PM (lunch rush) and 6:00 PM – 8:00 PM (evening Nyama Choma rush). Recommend pre-grilling 15 kg beef before 5:30 PM.";
      } else {
        response = `Based on Kato's Kitchen last 30 days of data: Today's sales (KSh 58,420) are performing +12.4% above average. Evening footfall drives 42% of total revenue.`;
      }

      setAiAnswer(response);
      setIsAiLoading(false);
    }, 600);
  };

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-[1600px] mx-auto">
      <PageHeader
        title="Habari, Kato 👋"
        subtitle="Kato's Kitchen runs autonomously — your full report lands every evening after close of business."
        action={
          <div className="flex items-center gap-2">
            <Badge variant="outline" className="gap-1.5 py-1 px-2.5 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20">
              <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 animate-pulse" />Live
            </Badge>
            <Button variant="outline" size="sm">Today</Button>
          </div>
        }
      />

      {/* CLOSE-OF-BUSINESS REPORT CARD WITH ACTIVE PREVIEW DIALOG */}
      <Card className="p-5 shadow-soft border-primary/30">
        <div className="flex flex-col sm:flex-row sm:items-center gap-4 justify-between">
          <div className="flex items-start gap-3">
            <div className="h-10 w-10 rounded-xl gradient-primary grid place-items-center shrink-0">
              <Sparkles className="h-5 w-5 text-primary-foreground" />
            </div>
            <div>
              <h3 className="font-semibold">Close-of-business AI report</h3>
              <p className="text-xs text-muted-foreground mt-0.5 leading-relaxed max-w-xl">
                Every day at 9:00 PM the AI reconciles all M-Pesa transactions, flags unpaid orders, ranks best-selling
                dishes and drafts tomorrow's shopping list — then sends it to you. Nothing else needs your attention.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <Badge variant="secondary" className="py-1">Next: 9:00 PM</Badge>

            <Dialog open={reportOpen} onOpenChange={setReportOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" size="sm" className="border-primary/40 text-primary hover:bg-primary/10">
                  <FileText className="h-4 w-4 mr-1.5" /> Preview report
                </Button>
              </DialogTrigger>
              <DialogContent className="sm:max-w-xl max-h-[85vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle className="flex items-center gap-2">
                    <FileText className="h-5 w-5 text-primary" /> Daily Close-of-Business AI Summary
                  </DialogTitle>
                </DialogHeader>

                <div className="space-y-4 py-2 text-sm">
                  {/* Financial Stats */}
                  <div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5 bg-muted/30 p-3.5 rounded-xl border">
                    <div>
                      <div className="text-[11px] text-muted-foreground font-medium">Total Sales</div>
                      <div className="text-lg font-bold text-foreground">{KES(58420)}</div>
                    </div>
                    <div>
                      <div className="text-[11px] text-muted-foreground font-medium">Net Profit</div>
                      <div className="text-lg font-bold text-emerald-600">{KES(16780)}</div>
                    </div>
                    <div>
                      <div className="text-[11px] text-muted-foreground font-medium">Transactions</div>
                      <div className="text-lg font-bold text-foreground">184 orders</div>
                    </div>
                  </div>

                  {/* M-Pesa Reconciliation */}
                  <div className="p-3.5 rounded-xl border border-mpesa/30 bg-mpesa/5 space-y-1.5">
                    <div className="font-semibold text-xs text-mpesa flex items-center gap-1.5">
                      <CheckCircle2 className="h-4 w-4 text-mpesa" /> M-Pesa Till 174379 Reconciled
                    </div>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      100% of M-Pesa transactions (KSh 42,062) matched perfectly with POS checkouts. 0 unpaid order discrepancies.
                    </p>
                  </div>

                  {/* Best Selling Dishes */}
                  <div className="space-y-2">
                    <div className="font-semibold text-xs text-muted-foreground uppercase tracking-wider">Top Performing Dishes</div>
                    <div className="space-y-1.5">
                      <div className="flex justify-between items-center text-xs p-2 rounded-lg bg-card border">
                        <span className="font-medium">1. Nyama Choma (½ kg)</span>
                        <span className="font-bold">84 plates served ({KES(71400)})</span>
                      </div>
                      <div className="flex justify-between items-center text-xs p-2 rounded-lg bg-card border">
                        <span className="font-medium">2. Brown Ugali</span>
                        <span className="font-bold">132 plates served ({KES(13200)})</span>
                      </div>
                      <div className="flex justify-between items-center text-xs p-2 rounded-lg bg-card border">
                        <span className="font-medium">3. Pilau ya Kuku</span>
                        <span className="font-bold">76 plates served ({KES(34200)})</span>
                      </div>
                    </div>
                  </div>

                  {/* Market Shopping List AI Restock */}
                  <div className="p-3.5 rounded-xl border border-amber-500/30 bg-amber-500/5 space-y-1.5">
                    <div className="font-semibold text-xs text-amber-700 dark:text-amber-300 flex items-center gap-1.5">
                      <AlertTriangle className="h-4 w-4" /> Tomorrow's Market Restock Draft
                    </div>
                    <p className="text-xs text-muted-foreground leading-relaxed">
                      AI suggests buying: <strong>Fresh Tilapia (10 kg)</strong>, <strong>Tomatoes (8 kg)</strong>, <strong>Kuku Kienyeji (6 pcs)</strong>. Estimated market cost: <strong>{KES(7650)}</strong>.
                    </p>
                  </div>
                </div>

                <DialogFooter className="flex-col sm:flex-row gap-2">
                  <Button
                    variant="outline"
                    className="sm:flex-1 text-xs"
                    onClick={() => {
                      toast.success("Report downloaded (PDF)", { description: "Saved Kato_Kitchen_COB_Report.pdf" });
                    }}
                  >
                    <Download className="h-4 w-4 mr-1.5" /> Download PDF
                  </Button>
                  <Button
                    className="sm:flex-1 bg-mpesa hover:bg-mpesa/90 text-white border-0 text-xs"
                    onClick={handleSendReportWhatsApp}
                  >
                    <MessageCircle className="h-4 w-4 mr-1.5" /> Send to WhatsApp
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </Card>

      {/* STAT CARDS */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard label="Today's sales" value={KES(58420)} delta="+12.4% vs yesterday" tone="success" icon={<Wallet className="h-5 w-5" />} />
        <StatCard label="Profit" value={KES(16780)} delta="+8.2%" tone="default" icon={<TrendingUp className="h-5 w-5" />} />
        <StatCard label="Transactions" value="184" delta="+22 vs avg" tone="mpesa" icon={<Receipt className="h-5 w-5" />} />
        <StatCard label="Items sold" value="412" tone="warning" icon={<ShoppingBag className="h-5 w-5" />} />
      </div>

      {/* CHARTS AND AI INSIGHTS CARD */}
      <div className="grid lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-2 p-5 shadow-soft">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h3 className="font-semibold">Sales & profit trend</h3>
              <p className="text-xs text-muted-foreground">Last 7 days</p>
            </div>
            <div className="flex gap-3 text-xs">
              <span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-sm bg-primary" />Sales</span>
              <span className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-sm bg-success" />Profit</span>
            </div>
          </div>
          <ResponsiveContainer width="100%" height={260}>
            <AreaChart data={salesTrend} margin={{ left: -10, right: 5, top: 5 }}>
              <defs>
                <linearGradient id="g1" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="var(--color-primary)" stopOpacity={0.4} />
                  <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0} />
                </linearGradient>
                <linearGradient id="g2" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="var(--color-success)" stopOpacity={0.35} />
                  <stop offset="95%" stopColor="var(--color-success)" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis dataKey="day" stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
              <YAxis stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} tickFormatter={(v) => `${v / 1000}k`} />
              <Tooltip contentStyle={{ background: "var(--color-card)", border: "1px solid var(--color-border)", borderRadius: 12, fontSize: 12 }} formatter={(v: number) => KES(v)} />
              <Area type="monotone" dataKey="sales" stroke="var(--color-primary)" fill="url(#g1)" strokeWidth={2.5} />
              <Area type="monotone" dataKey="profit" stroke="var(--color-success)" fill="url(#g2)" strokeWidth={2.5} />
            </AreaChart>
          </ResponsiveContainer>
        </Card>

        {/* AI INSIGHTS & INTERACTIVE AI QUESTION DIALOG */}
        <Card className="p-5 shadow-soft flex flex-col justify-between">
          <div>
            <div className="flex items-center gap-2 mb-3">
              <div className="h-8 w-8 rounded-lg gradient-primary grid place-items-center">
                <Sparkles className="h-4 w-4 text-primary-foreground" />
              </div>
              <div>
                <h3 className="font-semibold text-sm">KaliPOS AI</h3>
                <p className="text-[11px] text-muted-foreground">Today's smart insights</p>
              </div>
            </div>
            <div className="space-y-2">
              {aiInsights.map((i) => (
                <div
                  key={i.title}
                  onClick={() => {
                    handleAskAi(i.title);
                    setAiModalOpen(true);
                  }}
                  className="rounded-xl border bg-muted/30 p-3 hover:bg-muted/50 transition-colors cursor-pointer"
                  title="Click to ask AI about this insight"
                >
                  <div className="flex items-start gap-2.5">
                    <span className="text-lg leading-none mt-0.5">{i.icon}</span>
                    <div className="min-w-0">
                      <div className="text-sm font-medium">{i.title}</div>
                      <div className="text-xs text-muted-foreground mt-0.5 leading-relaxed">{i.body}</div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <Dialog open={aiModalOpen} onOpenChange={setAiModalOpen}>
            <DialogTrigger asChild>
              <Button variant="ghost" size="sm" className="w-full mt-3 text-primary justify-between hover:bg-primary/10">
                Ask AI a question <ArrowRight className="h-3.5 w-3.5" />
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-md">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <Bot className="h-5 w-5 text-primary" /> Ask KaliPOS AI
                </DialogTitle>
              </DialogHeader>

              <div className="space-y-3 py-2">
                <div className="space-y-1.5">
                  <Label className="text-xs text-muted-foreground">Select a recommended query or enter your question:</Label>
                  <div className="flex flex-wrap gap-1.5">
                    {[
                      "What products made the least profit this week?",
                      "What stock should I reorder today?",
                      "Predict tomorrow's busiest hours",
                    ].map((p) => (
                      <button
                        key={p}
                        onClick={() => handleAskAi(p)}
                        className="text-xs px-2.5 py-1 rounded-full border bg-muted/40 hover:bg-primary/10 hover:text-primary transition-colors text-left"
                      >
                        {p}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex gap-2">
                  <Input
                    placeholder="e.g. Which dish sells most on weekends?"
                    value={aiQuestion}
                    onChange={(e) => setAiQuestion(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && aiQuestion.trim()) {
                        handleAskAi(aiQuestion);
                      }
                    }}
                  />
                  <Button
                    size="icon"
                    className="gradient-primary border-0 shrink-0"
                    onClick={() => handleAskAi(aiQuestion)}
                    disabled={isAiLoading || !aiQuestion.trim()}
                  >
                    <Send className="h-4 w-4" />
                  </Button>
                </div>

                {isAiLoading && (
                  <div className="p-4 text-center text-xs text-muted-foreground animate-pulse">
                    Analyzing Kato's Kitchen sales data... ✨
                  </div>
                )}

                {aiAnswer && (
                  <div className="p-3.5 rounded-xl border bg-card text-xs leading-relaxed space-y-2 animate-slide-up">
                    <div className="font-semibold text-primary flex items-center gap-1.5">
                      <Sparkles className="h-3.5 w-3.5" /> AI Recommendation:
                    </div>
                    <p className="text-foreground">{aiAnswer}</p>
                  </div>
                )}
              </div>

              <DialogFooter className="flex-col sm:flex-row gap-2">
                <Button variant="outline" className="w-full" onClick={() => setAiModalOpen(false)}>
                  Close
                </Button>
                <Button
                  className="w-full gradient-primary border-0"
                  onClick={() => {
                    setAiModalOpen(false);
                    navigate({ to: "/ai" });
                  }}
                >
                  Open Full AI Assistant <ArrowRight className="h-4 w-4 ml-1.5" />
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </Card>
      </div>

      <div className="grid lg:grid-cols-3 gap-4">
        <Card className="p-5 shadow-soft">
          <h3 className="font-semibold mb-1">Payment methods</h3>
          <p className="text-xs text-muted-foreground mb-2">Today's split</p>
          <ResponsiveContainer width="100%" height={180}>
            <PieChart>
              <Pie data={paymentSplit} dataKey="value" innerRadius={45} outerRadius={70} paddingAngle={3}>
                {paymentSplit.map((e, i) => <Cell key={i} fill={e.color} />)}
              </Pie>
              <Tooltip contentStyle={{ background: "var(--color-card)", border: "1px solid var(--color-border)", borderRadius: 12, fontSize: 12 }} />
            </PieChart>
          </ResponsiveContainer>
          <div className="space-y-1.5 mt-2">
            {paymentSplit.map((p) => (
              <div key={p.name} className="flex items-center justify-between text-xs">
                <span className="flex items-center gap-2"><span className="h-2 w-2 rounded-sm" style={{ background: p.color }} />{p.name}</span>
                <span className="font-semibold">{p.value}%</span>
              </div>
            ))}
          </div>
        </Card>

        <Card className="lg:col-span-2 p-5 shadow-soft">
          <div className="flex items-center justify-between mb-3">
            <div>
              <h3 className="font-semibold">Top selling dishes</h3>
              <p className="text-xs text-muted-foreground">By plates served today</p>
            </div>
          </div>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={topProducts} margin={{ left: -10 }}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border)" vertical={false} />
              <XAxis dataKey="name" stroke="var(--color-muted-foreground)" fontSize={10} tickLine={false} axisLine={false} interval={0} angle={-15} textAnchor="end" height={60} />
              <YAxis stroke="var(--color-muted-foreground)" fontSize={11} tickLine={false} axisLine={false} />
              <Tooltip contentStyle={{ background: "var(--color-card)", border: "1px solid var(--color-border)", borderRadius: 12, fontSize: 12 }} />
              <Bar dataKey="units" fill="var(--color-primary)" radius={[8, 8, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </Card>
      </div>

      <Card className="p-5 shadow-soft">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="font-semibold">Branch performance</h3>
            <p className="text-xs text-muted-foreground">Compare your shops at a glance</p>
          </div>
          <Button variant="outline" size="sm">Manage branches</Button>
        </div>
        <div className="grid sm:grid-cols-3 gap-3">
          {branches.map((b) => (
            <div key={b.id} className="rounded-xl border p-4 hover:border-primary transition-colors">
              <div className="text-sm font-medium">{b.name}</div>
              <div className="text-xl font-bold mt-1">{KES(b.sales)}</div>
              <div className={`text-xs mt-1 font-medium ${b.growth >= 0 ? "text-success" : "text-destructive"}`}>
                {b.growth >= 0 ? "↑" : "↓"} {Math.abs(b.growth)}% this week
              </div>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}

